name: CI Tests and Email Notification

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Installation des dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Exécution des tests
        id: pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q

      - name: Notification par e-mail
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'Résultat des tests CI pour le script de sauvegarde'
          html_body: |
            <html>
              <body style="font-family: Arial, sans-serif; line-height: 1.5; background-color: #f7f7f7; padding: 20px;">
                <div style="max-width: 600px; margin: auto; background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
                  <h2 style="color: #2E86C1; text-align: center;">Résultat des tests CI</h2>
                  <p>Bonjour,</p>
                  <p>Les tests de l'intégration continue pour le script de sauvegarde ont été exécutés avec succès.</p>
                  <p>Pour plus de détails, veuillez consulter l'onglet <a href="${{ github.server_url }}/${{ github.repository }}/actions" style="color: #2874A6; text-decoration: none;">Actions</a> sur GitHub.</p>
                  <br>
                  <p>Cordialement,</p>
                  <p><strong>L'équipe CI</strong></p>
                </div>
              </body>
            </html>
          to: charlesdevif@hotmail.fr
          from: ${{ secrets.EMAIL_USERNAME }}
